#!/usr/bin/env bash

monitorInfo=$(hyprctl monitors -j)

numOfMonitors=$(echo $monitorInfo | jq length)


echo $numOfMonitors

if [[ $numOfMonitors == 2 ]]; then
	temp=$(echo $monitorInfo | jq '.[0].activeWorkspace.id')
	echo $temp


	hyprctl --batch
fi
