local mode = require("lualine.utils.mode")

mode.map = {
	["n"]      = "NORMAL",
	["no"]     = "O-PENDING",
	["nov"]    = "O-PENDING",
	["noV"]    = "O-PENDING",
	["no\22"] = "O-PENDING",
	["niI"]    = "NORMAL",
	["niR"]    = "NORMAL",
	["niV"]    = "NORMAL",
	["nt"]     = "NORMAL",
	["ntT"]    = "NORMAL",
	["v"]      = "VISUAL",
	["vs"]     = "VISUAL",
	["V"]      = "V-LINE",
	["Vs"]     = "V-LINE",
	["\22"]   = "V-BLOCK",
	["\22s"]  = "V-BLOCK",
	["s"]      = "SELECT",
	["S"]      = "S-LINE",
	["\19"]   = "S-BLOCK",
	["i"]      = "INSERT",
	["ic"]     = "INSERT",
	["ix"]     = "INSERT",
	["R"]      = "REPLACE",
	["Rc"]     = "REPLACE",
	["Rx"]     = "REPLACE",
	["Rv"]     = "V-REPLACE",
	["Rvc"]    = "V-REPLACE",
	["Rvx"]    = "V-REPLACE",
	["c"]      = "COMMAND",
	["cv"]     = "EX",
	["ce"]     = "EX",
	["r"]      = "REPLACE",
	["rm"]     = "MORE",
	["r?"]     = "CONFIRM",
	["!"]      = "SHELL",
	["t"]      = "TERMINAL",
}

require("lualine").setup {
	options = {
		icons_enabled = false,
		theme = "auto",
		component_separators = { left = "|", right = "|"},
		section_separators = { left = "", right = ""},
		always_divide_middle = true,
		globalstatus = true,
	},
	sections = {
		lualine_a = {"mode"},
		lualine_b = {"branch", "diff"},
		lualine_c = {"filename"},
		lualine_x = {"encoding", "filetype"},
		lualine_y = {"progress"},
		lualine_z = {"location"}
	},
	extensions = {}
}
